version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: auladockercontainer
    environment:
      POSTGRES_DB: auladocker
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5431:5432"
    restart: always